application: atom-server-appengine
version: 1
runtime: java

welcome_files:
  - index.html
  - index.jsp

handlers:
# All Atom test requests go here.
  - url: /test/*
    servlet: inspiracio.atom.TestServlet
    name: test

# All Atom requests go here.
  - url: /atom/*
    servlet: inspiracio.atom.IAtomServlet
    name: atom
    init_params:
      beanPackage: inspiracio
#    login: required
      
#web_xml: |
#  <error-page>
#    <error-code>500</error-code>
#    <location>/errors/servererror.jsp</location>
#  </error-page>